// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/containers/[project].ts";
import * as $2 from "./routes/api/project.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/project/[name]/[container].tsx";
import * as $5 from "./routes/project/[project].tsx";
import * as $$0 from "./islands/ProjectDetails.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/containers/[project].ts": $1,
    "./routes/api/project.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/project/[name]/[container].tsx": $4,
    "./routes/project/[project].tsx": $5,
  },
  islands: {
    "./islands/ProjectDetails.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
