name: Deploy Production

on:
  push:
    branches: [ "production" ]

env:
  APPLICATION_NAME: "boxer"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Set image tag
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $APPLICATION_NAME:${{ steps.tag.outputs.tag }}

    - name: Export Docker image to archive
      run: docker save --output "$APPLICATION_NAME.tar.gz" $APPLICATION_NAME:${{ steps.tag.outputs.tag }}

    - uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${{ env.APPLICATION_NAME }}.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [quality, build]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: image
        path: ${{ env.APPLICATION_NAME }}.tar.gz

    - name: Copy image to own infrastructure
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "${{ env.APPLICATION_NAME }}.tar.gz"
        target: "${{ env.APPLICATION_NAME }}"
        
    - name: Deploy to own infrastructure
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load < "${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.tar.gz"
          docker tag "${{ env.APPLICATION_NAME }}:${{ steps.tag.outputs.tag }}" "${{ env.APPLICATION_NAME }}:latest"
          docker compose --project-directory "${{ env.APPLICATION_NAME }}" up -d
